const rows=[['6:00 – 6:15 AM','WAKE UP','Gratitude & Plan Your Day','Positive Start','☀️','normal'],['6:15 – 6:45 AM','EXERCISE / YOGA / WALK','Stay Fit, Stay Sharp','Physical & Mental Fitness','🏃','normal'],['6:45 – 7:15 AM','FRESHEN UP','Personal Care','Refresh & Rejuvenate','🚿','normal'],['7:15 – 7:45 AM','BREAKFAST','Eat Healthy, Think Better','Nutrition & Energy','🥗','normal'],['7:45 – 10:15 AM','ELECTRICAL ENGINEERING (THEORY)','Core Subject – ESE / MPSC / SSC JE / RRB JE','Concept Building','📖','red'],['10:15 – 10:30 AM','SHORT BREAK','Tea / Break','Relax & Re-energize','☕','normal'],['10:30 – 1:00 PM','ELECTRICAL ENGINEERING (NUMERICALS)','Numericals + Problem Solving','Practice & Accuracy','🧮','red'],['1:00 – 2:00 PM','LUNCH & REST','Good Food, Good Mood','Recharge Yourself','🍽️','normal'],['2:00 – 4:00 PM','PYQs & MCQs PRACTICE','ESE / SSC JE / RRB JE','Exam Familiarity','📝','red'],['4:00 – 4:30 PM','TEA BREAK','Short Break, Fresh Mind','Relax','☕','normal'],['4:30 – 5:30 PM','QUANTITATIVE APTITUDE','SSC / Railways / CGL','Speed & Accuracy','Σ','blue'],['5:30 – 6:30 PM','REASONING ABILITY','SSC / Railways / CGL','Logical Thinking','🧠','purple'],['6:30 – 7:30 PM','GENERAL STUDIES & CURRENT AFFAIRS','Polity, History, Geography, Economy, Science, CA','Awareness & Knowledge','🌐','green'],['7:30 – 8:15 PM','DINNER & FAMILY TIME','Take a Break, Stay Connected','Relax & Refresh','👨‍👩‍👧','normal'],['8:15 – 9:15 PM','ENGLISH','Grammar, Vocabulary, RC','CGL / SSC / All Exams','ABC','blue'],['9:15 – 10:00 PM','REVISION & MOCK ANALYSIS','Mock Test / Error Analysis / Short Notes','Improve & Stay Ahead','🎯','purple'],['10:00 PM','SLEEP','Good Sleep, Better Tomorrow','7 – 8 Hours Sleep','🌙','normal']];
const quotes=[['The harder you work for something, the greater you’ll feel when you achieve it.','mountain'],['Don’t stop when you’re tired. Stop when you’re done.','sunrise'],['Discipline today, success tomorrow.','hourglass'],['Small daily improvements are the key to stunning results.','summit'],['Your future is created by what you do today, not tomorrow.','lamp']];
const done=new Set();
const schedule=document.getElementById('schedule');
schedule.innerHTML=rows.map((r,i)=>`<tr data-i="${i}" class="${r[5]}"><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td class="ico">${r[4]}</td></tr>`).join('');
document.getElementById('quotes').innerHTML=quotes.map(q=>`<div class="quote ${q[1]}"><span>“</span><p>${q[0]}</p><b>”</b></div>`).join('');
schedule.addEventListener('click',e=>{const tr=e.target.closest('tr'); if(!tr)return; const i=+tr.dataset.i; done.has(i)?done.delete(i):done.add(i); tr.classList.toggle('done'); update();});
function minutes(label){const m=label.match(/(\d+):(\d+)\s*(AM|PM)/); if(!m)return null; let h=+m[1],min=+m[2]; if(m[3]==='PM'&&h!==12)h+=12; if(m[3]==='AM'&&h===12)h=0; return h*60+min;}
function activeIndex(now){const mins=now.getHours()*60+now.getMinutes(); for(let i=0;i<rows.length;i++){const start=minutes(rows[i][0]); const end=minutes(rows[i+1]?.[0]||'10:00 PM'); if(start!==null&&mins>=start&&mins<end)return i;} return rows.length-1;}
function update(){const now=new Date(); const active=activeIndex(now); document.querySelectorAll('#schedule tr').forEach((tr,i)=>tr.classList.toggle('active',i===active)); const pct=Math.round(done.size/rows.length*100); document.getElementById('current-session').textContent=rows[active][1]; document.getElementById('clock').textContent=now.toLocaleTimeString(); document.getElementById('progress').textContent=pct+'%'; document.getElementById('meter').value=pct; document.getElementById('today').textContent=now.toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'short'});}
update(); setInterval(update,1000);
